const API_BASE_URL_DEVELOPMENT = 'https://localhost:7031';
const API_BASE_URL_PRODUCTION = 'https://localhost:7031';

const ENDPOINTS = {
    GET_ALL_DOCTORS:'api/Doctors',
    GET_DOCTOR_BY_ID:'api/Doctors/{id}',
    CREATE_DOCTOR:'api/Doctors',
    UPDATE_DOCTOR:'api/Doctors/{id}',
    DELETE_DOCTOR_BY_ID:'api/Doctors/{id}',
    DELETE_RANGE_DOCTORS:'api/Doctors/Delete'
};

const development = {
    API_URL_GET_ALL_DOCTORS:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_DOCTORS}`,
    API_URL_GET_DOCTOR_BY_ID:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_DOCTOR_BY_ID}`,
    API_URL_CREATE_DOCTOR:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_DOCTOR}`,
    API_URL_UPDATE_DOCTOR:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_DOCTOR}`,
    API_URL_DELETE_DOCTOR_BY_ID:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_DOCTOR_BY_ID}`,
    API_URL_DELETE_RANGE_DOCTORS:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_RANGE_DOCTORS}`,
};

const production = {
    API_URL_GET_ALL_DOCTORS:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_DOCTORS}`,
    API_URL_GET_DOCTOR_BY_ID:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_DOCTOR_BY_ID}`,
    API_URL_CREATE_DOCTOR:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_DOCTOR}`,
    API_URL_UPDATE_DOCTOR:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_DOCTOR}`,
    API_URL_DELETE_DOCTOR_BY_ID:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_DOCTOR_BY_ID}`,
    API_URL_DELETE_RANGE_DOCTORS:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_RANGE_DOCTORS}`,
};


const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;




